// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: order.proto

package orderService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ItemsIDs      []string               `protobuf:"bytes,2,rep,name=ItemsIDs,proto3" json:"ItemsIDs,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=Created,proto3" json:"Created,omitempty"`
	Paid          bool                   `protobuf:"varint,4,opt,name=Paid,proto3" json:"Paid,omitempty"`
	Submitted     bool                   `protobuf:"varint,5,opt,name=Submitted,proto3" json:"Submitted,omitempty"`
	Delivering    bool                   `protobuf:"varint,6,opt,name=Delivering,proto3" json:"Delivering,omitempty"`
	Delivered     bool                   `protobuf:"varint,7,opt,name=Delivered,proto3" json:"Delivered,omitempty"`
	Canceled      bool                   `protobuf:"varint,8,opt,name=Canceled,proto3" json:"Canceled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Order) GetItemsIDs() []string {
	if x != nil {
		return x.ItemsIDs
	}
	return nil
}

func (x *Order) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *Order) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *Order) GetSubmitted() bool {
	if x != nil {
		return x.Submitted
	}
	return false
}

func (x *Order) GetDelivering() bool {
	if x != nil {
		return x.Delivering
	}
	return false
}

func (x *Order) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *Order) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	ItemID        []string               `protobuf:"bytes,2,rep,name=ItemID,proto3" json:"ItemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

func (x *CreateOrderReq) GetItemID() []string {
	if x != nil {
		return x.ItemID
	}
	return nil
}

type CreateOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRes) Reset() {
	*x = CreateOrderRes{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRes) ProtoMessage() {}

func (x *CreateOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRes.ProtoReflect.Descriptor instead.
func (*CreateOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRes) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type PayOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderReq) Reset() {
	*x = PayOrderReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderReq) ProtoMessage() {}

func (x *PayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderReq.ProtoReflect.Descriptor instead.
func (*PayOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *PayOrderReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type PayOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderRes) Reset() {
	*x = PayOrderRes{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRes) ProtoMessage() {}

func (x *PayOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRes.ProtoReflect.Descriptor instead.
func (*PayOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *PayOrderRes) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type SubmitOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderReq) Reset() {
	*x = SubmitOrderReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderReq) ProtoMessage() {}

func (x *SubmitOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderReq.ProtoReflect.Descriptor instead.
func (*SubmitOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitOrderReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type SubmitOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRes) Reset() {
	*x = SubmitOrderRes{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRes) ProtoMessage() {}

func (x *SubmitOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRes.ProtoReflect.Descriptor instead.
func (*SubmitOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitOrderRes) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type GetOrderByIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDReq) Reset() {
	*x = GetOrderByIDReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDReq) ProtoMessage() {}

func (x *GetOrderByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDReq.ProtoReflect.Descriptor instead.
func (*GetOrderByIDReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderByIDReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type GetOrderByIDRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRes) Reset() {
	*x = GetOrderByIDRes{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRes) ProtoMessage() {}

func (x *GetOrderByIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRes.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderByIDRes) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	ItemID        []string               `protobuf:"bytes,2,rep,name=ItemID,proto3" json:"ItemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderReq) Reset() {
	*x = UpdateOrderReq{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderReq) ProtoMessage() {}

func (x *UpdateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderReq.ProtoReflect.Descriptor instead.
func (*UpdateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOrderReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

func (x *UpdateOrderReq) GetItemID() []string {
	if x != nil {
		return x.ItemID
	}
	return nil
}

type UpdateOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRes) Reset() {
	*x = UpdateOrderRes{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRes) ProtoMessage() {}

func (x *UpdateOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRes.ProtoReflect.Descriptor instead.
func (*UpdateOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\forderService\"\xd9\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bItemsIDs\x18\x02 \x03(\tR\bItemsIDs\x12\x18\n" +
	"\aCreated\x18\x03 \x01(\bR\aCreated\x12\x12\n" +
	"\x04Paid\x18\x04 \x01(\bR\x04Paid\x12\x1c\n" +
	"\tSubmitted\x18\x05 \x01(\bR\tSubmitted\x12\x1e\n" +
	"\n" +
	"Delivering\x18\x06 \x01(\bR\n" +
	"Delivering\x12\x1c\n" +
	"\tDelivered\x18\a \x01(\bR\tDelivered\x12\x1a\n" +
	"\bCanceled\x18\b \x01(\bR\bCanceled\"J\n" +
	"\x0eCreateOrderReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\x12\x16\n" +
	"\x06ItemID\x18\x02 \x03(\tR\x06ItemID\"2\n" +
	"\x0eCreateOrderRes\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"/\n" +
	"\vPayOrderReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"/\n" +
	"\vPayOrderRes\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"2\n" +
	"\x0eSubmitOrderReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"2\n" +
	"\x0eSubmitOrderRes\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"3\n" +
	"\x0fGetOrderByIDReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"<\n" +
	"\x0fGetOrderByIDRes\x12)\n" +
	"\x05Order\x18\x01 \x01(\v2\x13.orderService.OrderR\x05Order\"J\n" +
	"\x0eUpdateOrderReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\x12\x16\n" +
	"\x06ItemID\x18\x02 \x03(\tR\x06ItemID\"\x10\n" +
	"\x0eUpdateOrderRes2\xff\x02\n" +
	"\forderService\x12I\n" +
	"\vCreateOrder\x12\x1c.orderService.CreateOrderReq\x1a\x1c.orderService.CreateOrderRes\x12@\n" +
	"\bPayOrder\x12\x19.orderService.PayOrderReq\x1a\x19.orderService.PayOrderRes\x12I\n" +
	"\vSubmitOrder\x12\x1c.orderService.SubmitOrderReq\x1a\x1c.orderService.SubmitOrderRes\x12L\n" +
	"\fGetOrderByID\x12\x1d.orderService.GetOrderByIDReq\x1a\x1d.orderService.GetOrderByIDRes\x12I\n" +
	"\vUpdateOrder\x12\x1c.orderService.UpdateOrderReq\x1a\x1c.orderService.UpdateOrderResB\x11Z\x0f./;orderServiceb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_order_proto_goTypes = []any{
	(*Order)(nil),           // 0: orderService.Order
	(*CreateOrderReq)(nil),  // 1: orderService.CreateOrderReq
	(*CreateOrderRes)(nil),  // 2: orderService.CreateOrderRes
	(*PayOrderReq)(nil),     // 3: orderService.PayOrderReq
	(*PayOrderRes)(nil),     // 4: orderService.PayOrderRes
	(*SubmitOrderReq)(nil),  // 5: orderService.SubmitOrderReq
	(*SubmitOrderRes)(nil),  // 6: orderService.SubmitOrderRes
	(*GetOrderByIDReq)(nil), // 7: orderService.GetOrderByIDReq
	(*GetOrderByIDRes)(nil), // 8: orderService.GetOrderByIDRes
	(*UpdateOrderReq)(nil),  // 9: orderService.UpdateOrderReq
	(*UpdateOrderRes)(nil),  // 10: orderService.UpdateOrderRes
}
var file_order_proto_depIdxs = []int32{
	0,  // 0: orderService.GetOrderByIDRes.Order:type_name -> orderService.Order
	1,  // 1: orderService.orderService.CreateOrder:input_type -> orderService.CreateOrderReq
	3,  // 2: orderService.orderService.PayOrder:input_type -> orderService.PayOrderReq
	5,  // 3: orderService.orderService.SubmitOrder:input_type -> orderService.SubmitOrderReq
	7,  // 4: orderService.orderService.GetOrderByID:input_type -> orderService.GetOrderByIDReq
	9,  // 5: orderService.orderService.UpdateOrder:input_type -> orderService.UpdateOrderReq
	2,  // 6: orderService.orderService.CreateOrder:output_type -> orderService.CreateOrderRes
	4,  // 7: orderService.orderService.PayOrder:output_type -> orderService.PayOrderRes
	6,  // 8: orderService.orderService.SubmitOrder:output_type -> orderService.SubmitOrderRes
	8,  // 9: orderService.orderService.GetOrderByID:output_type -> orderService.GetOrderByIDRes
	10, // 10: orderService.orderService.UpdateOrder:output_type -> orderService.UpdateOrderRes
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
